### ISSUE TITLE
Does not compile on STM32 CubeIDE 1.13.0

### ISSUE THREAD

**Issue by MaxPohlRP** [eez-open/modular-psu-firmware#328]
Hi, 
which version did you used for compiling?
With Version 1.13.0 i got (at least) 3 errors.

1. ..\Core\Src\sysmem.c:37:1: error: unknown type name 'caddr_t'
2. ..\Core\Src\sysmem.c:55:17: error: 'caddr_t' undeclared (first use in this function)
3. ..\Core\Src\sysmem.c:55:17: note: each undeclared identifier is reported only once for each function it appears in
..\Core\Src\sysmem.c:55:25: error: expected ';' before 'prev_heap_end'

Do you have any idea? Maybe its just due to a change in the IDE

**Comment by mvladic** [comment]
I'm currently on version 1.14.1 which also has that problem. You can fix this like following:

#if defined(caddr_t) // ADD THIS LINE!
caddr_t _sbrk(int incr)
{
  // ...
}
#endif // AND THIS LINE!

Also, note that master branch is version "1.8.0 Alpha" which is never released. Branch [dev_1.7.6](https://github.com/eez-open/modular-psu-firmware/tree/dev_1.7.6) contains the latest released version.
